import type { Meta, StoryObj } from '@storybook/react';
import { KeyValueFilter } from './KeyValueFilter';

const meta = {
    title: 'Filters/KeyValueFilter',
    component: KeyValueFilter,
    parameters: {
        layout: 'centered',
    },
    tags: ['autodocs'],
    argTypes: {
        keyName: { control: 'text' },
        values: { control: 'object' },
        includeAll: { control: 'boolean' },
        label: { control: 'text' },
        allLabel: { control: 'text' },
    },
} satisfies Meta<typeof KeyValueFilter>;

export default meta;
type Story = StoryObj<typeof meta>;

export const StatusFilter: Story = {
    args: {
        keyName: 'status',
        values: [
            { value: 'CURRENT', label: 'Current' },
            { value: 'MISSING', label: 'Missing' },
            { value: 'OUTDATED', label: 'Out-of-date' },
        ],
        includeAll: true,
        label: 'Status:',
        allLabel: 'All Statuses',
    },
    parameters: {
        docs: {
            description: {
                story: 'KeyValueFilter configured as a resource status filter with "All" option',
            },
        },
    },
};

export const LocaleCodeFilter: Story = {
    args: {
        keyName: 'localeCode',
        values: [
            { value: 'en', label: 'English' },
            { value: 'es', label: 'Spanish' },
            { value: 'fr', label: 'French' },
            { value: 'de', label: 'German' },
        ],
        includeAll: true,
        label: 'Locale:',
        allLabel: 'All Locales',
    },
    parameters: {
        docs: {
            description: {
                story: 'KeyValueFilter configured as a locale code filter',
            },
        },
    },
};

export const JobIdFilter: Story = {
    args: {
        keyName: 'jobId',
        values: [
            { value: '1001', label: 'Job 1001' },
            { value: '1002', label: 'Job 1002' },
            { value: '1003', label: 'Job 1003' },
        ],
        includeAll: true,
        label: 'Job:',
        allLabel: 'All Jobs',
    },
    parameters: {
        docs: {
            description: {
                story: 'KeyValueFilter configured as a job ID filter',
            },
        },
    },
};

export const WithoutAllOption: Story = {
    args: {
        keyName: 'view',
        values: [
            { value: 'grid', label: 'Grid View' },
            { value: 'list', label: 'List View' },
            { value: 'compact', label: 'Compact View' },
        ],
        includeAll: false,
        label: 'View:',
    },
    parameters: {
        docs: {
            description: {
                story: 'KeyValueFilter without "All" option - requires selection',
            },
        },
    },
};

export const AutoGeneratedLabel: Story = {
    args: {
        keyName: 'category',
        values: [
            { value: 'docs', label: 'Documentation' },
            { value: 'ui', label: 'User Interface' },
            { value: 'api', label: 'API' },
        ],
        includeAll: true,
        allLabel: 'All Categories',
    },
    parameters: {
        docs: {
            description: {
                story: 'KeyValueFilter with auto-generated label from keyName',
            },
        },
    },
};

export const MinimalConfiguration: Story = {
    args: {
        keyName: 'mode',
        values: [
            { value: 'light', label: 'Light' },
            { value: 'dark', label: 'Dark' },
        ],
        includeAll: false,
    },
    parameters: {
        docs: {
            description: {
                story: 'Minimal KeyValueFilter configuration with just two options',
            },
        },
    },
};

export const InContainer: Story = {
    args: {
        keyName: 'status',
        values: [
            { value: 'CURRENT', label: 'Current' },
            { value: 'MISSING', label: 'Missing' },
            { value: 'OUTDATED', label: 'Out-of-date' },
        ],
        includeAll: true,
        label: 'Status:',
        allLabel: 'All Statuses',
    },
    parameters: {
        layout: 'fullscreen',
    },
    decorators: [
        (Story) => (
            <div
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '1rem',
                    padding: '2rem',
                    minWidth: '300px',
                }}
            >
                <Story />
                <Story />
                <Story />
            </div>
        ),
    ],
};
