import type { Meta, StoryObj } from '@storybook/react';
import { MetadataFilter } from './MetadataFilter';

const meta = {
    title: 'Filters/MetadataFilter',
    component: MetadataFilter,
    parameters: {
        layout: 'centered',
    },
    tags: ['autodocs'],
    argTypes: {
        keyName: { control: 'text' },
        values: { control: 'object' },
        includeAll: { control: 'boolean' },
        label: { control: 'text' },
        allLabel: { control: 'text' },
    },
} satisfies Meta<typeof MetadataFilter>;

export default meta;
type Story = StoryObj<typeof meta>;

export const StatusFilter: Story = {
    args: {
        keyName: 'status',
        values: [
            { value: 'approved', label: 'Approved' },
            { value: 'in-review', label: 'In Review' },
            { value: 'draft', label: 'Draft' },
        ],
        includeAll: true,
        label: 'File Status:',
        allLabel: 'All Statuses',
    },
    parameters: {
        docs: {
            description: {
                story: 'MetadataFilter configured as a file status filter with "All" option',
            },
        },
    },
};

export const PriorityFilter: Story = {
    args: {
        keyName: 'priority',
        values: [
            { value: 'high', label: 'High' },
            { value: 'medium', label: 'Medium' },
            { value: 'low', label: 'Low' },
        ],
        includeAll: true,
        label: 'Priority:',
        allLabel: 'All Priorities',
    },
    parameters: {
        docs: {
            description: {
                story: 'MetadataFilter configured as a priority filter',
            },
        },
    },
};

export const CategoryFilter: Story = {
    args: {
        keyName: 'category',
        values: [
            { value: 'documentation', label: 'Documentation' },
            { value: 'ui', label: 'User Interface' },
            { value: 'api', label: 'API' },
            { value: 'content', label: 'Content' },
        ],
        includeAll: true,
        label: 'Category:',
        allLabel: 'All Categories',
    },
    parameters: {
        docs: {
            description: {
                story: 'MetadataFilter configured as a category filter',
            },
        },
    },
};

export const WithoutAllOption: Story = {
    args: {
        keyName: 'type',
        values: [
            { value: 'dita', label: 'DITA' },
            { value: 'markdown', label: 'Markdown' },
            { value: 'html', label: 'HTML' },
        ],
        includeAll: false,
        label: 'File Type:',
    },
    parameters: {
        docs: {
            description: {
                story: 'MetadataFilter without "All" option - requires selection',
            },
        },
    },
};

export const AutoGeneratedLabel: Story = {
    args: {
        keyName: 'assignee',
        values: [
            { value: 'john', label: 'John Doe' },
            { value: 'jane', label: 'Jane Smith' },
            { value: 'bob', label: 'Bob Johnson' },
        ],
        includeAll: true,
        allLabel: 'All Assignees',
    },
    parameters: {
        docs: {
            description: {
                story: 'MetadataFilter with auto-generated label from keyName',
            },
        },
    },
};

export const MinimalConfiguration: Story = {
    args: {
        keyName: 'state',
        values: [
            { value: 'active', label: 'Active' },
            { value: 'inactive', label: 'Inactive' },
        ],
        includeAll: false,
    },
    parameters: {
        docs: {
            description: {
                story: 'Minimal MetadataFilter configuration with just two options',
            },
        },
    },
};

export const InContainer: Story = {
    args: {
        keyName: 'status',
        values: [
            { value: 'approved', label: 'Approved' },
            { value: 'in-review', label: 'In Review' },
            { value: 'draft', label: 'Draft' },
        ],
        includeAll: true,
        label: 'Status:',
        allLabel: 'All Statuses',
    },
    parameters: {
        layout: 'fullscreen',
    },
    decorators: [
        (Story) => (
            <div
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '1rem',
                    padding: '2rem',
                    minWidth: '300px',
                }}
            >
                <Story />
                <Story />
                <Story />
            </div>
        ),
    ],
};
